### ISSUE TITLE
Empfohlen: Weniger commit spam, Dateiänderungen statt komplette Dateien zu löschen

### ISSUE THREAD

**Issue by FabianAicheler** [MoeJoeTP/TPProteomikdaten#4]
Hallo, zwecks Übersichtlichkeit empehlen wir sehr, wenn möglich nicht einen Commit pro zugefügter/gelöschter Datei zu machen, sondern das in einem einzigen Commit bündeln.

Ebenso sollten für Codeänderungen nicht immer komplett neue Dateien hochgeladen werden, sondern die Änderungen betroffener Dateien commited werden.

(Außer natürlich falls sich die Dateistruktur grundlegenst geändert bsp eine Klasse nichtmehr benutzt wird.  Aber bsp wenn die main geändert wurde, sollte der Commit eine Änderung sein die dann in die master Branch reingemerged wird)

**Comment by JoergGamerdinger** [comment]
TOP 3 für unsere Teamrunde am 20.06.

**Comment by JoergGamerdinger** [comment]
Wurde in unserer Teamrunde am 20.06. diskutiert.
Als Lösungsansatz wurde ein gemeinsames HowToGit erarbeitet, welches unter Organisatorisches zu finden ist.
